# Build settings
markdown: kramdown
theme: minima
# remote_theme: pages-themes/minimal@v0.2.0

kramdown:
  math_engine: mathjax
  syntax_highlighter: rouge

header_pages:
  - README.md
  - setup.md
  - documentation.md

# The default date format, used if none is specified in the tag.
minima:
  date_format: "%b %-d, %Y"